server:
  port: ${SERVER_PORT:8080}

logging:
  file:
    path: ./logs
    name: application.log
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway-rw
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://54.177.245.226:3000}"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: false
      routes:
        - id: user_service_route
          uri: ${USER_SERVICE_URL:} http://user-service:8081 # http://localhost:8081
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: qa_service_route
          uri: ${QA_SERVICE_URL:http://qa-service:8082 } # http://localhost:8082
          predicates:
            - Path=/api/qa/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@inMemoryRateLimiter}"
                key-resolver: "#{@ipKeyResolver}"
                replenish-rate: 10000
                burst-capacity: 100000
                requested-tokens: 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
